--- 
services: 
  app: 
    build: ./application
    depends_on: 
      - postgres
    image: ethercis-app
    labels: 
      com.microsoft.acs.dcos.marathon.healthcheck: "true"
    ports: 
      - "8080:8080"
  postgres: 
    build: ./postgres
  
    environment: 
      POSTGRES_DB: ethercis
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      constraint: "hostname", "CLUSTER", "10.32.0.6"
    image: ethercis-db
    labels: 
      com.microsoft.acs.dcos.marathon.healthcheck: "true"
    ports: 
      - "5432:5432"
    volumes: 
      - "data:/var/lib/postgresql/data"
version: "2"
volumes: 
  data: ~
