version: "2"

services:

  app:
    # Build application using Dockerfile contained in application subfolder
    build: ./application
    # Name image
    image: ethercis-app
    # Map application container port 8080 to Docker port 8080
    ports:
      - "8080:8080"
      
    # Do not start application container until postgres service is started
    depends_on:
      - postgres
    labels:
     - 'com.microsoft.acs.dcos.marathon.vhost' :  'www.example.com' 
  postgres:
    # Build database using Dockerfile contained in postgres subfolder
    build: ./postgres
    # Name image
    image: ethercis-db
    
    ports:
      - "5432:5432"
